apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: getlink-dtd
  namespace: argocd
spec:
  description: GetLink DTD on the Azure for Students k3s VM
  sourceRepos:
    - https://github.com/dongtaiduc04-star/helm_v1.git
  destinations:
    - namespace: getlink-dtd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
